### ISSUE TITLE
dashboard 如何通过ip访问，不用localhost

### ISSUE THREAD

**Issue by china8chen** [AliyunContainerService/k8s-for-docker-desktop#38]
k8s 的dashboard，如何通过ip访问，而不是localhost

**Comment by khs1994** [comment]
https://github.com/AliyunContainerService/k8s-for-docker-desktop#%E9%85%8D%E7%BD%AE-kubeconfig-%E5%8F%AF%E8%B7%B3%E8%BF%87

`$ kubectl get all --all-namespaces` 获取到端口，IP:端口 访问即可

**Comment by khs1994** [comment]
https://github.com/AliyunContainerService/k8s-for-docker-desktop/blob/master/kubernetes-dashboard.yaml 这个文件加一个 `type: NodePort`

```yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8443
  selector:
k8s-app: kubernetes-dashboard
```
